spring:
  profiles:
    # Possible values are: logstash, mock-kfrei-rest-api, no-security-kfrei-mvg-eai, no-security-kfrei-rest-api
    active:
  application:
    name: kfrei-mvg-eai
  # Disable default error page to avoid exposing any internal information
  web:
    error:
      whitelabel:
        enabled: false
  http:
    clients:
      # Default timeouts for Spring RestClient calls
      connect-timeout: PT10S
      read-timeout: PT10S
  security:
    oauth2:
      # OAuth2 configuration for accessing the kfrei-mvg-eai
      resourceserver:
        jwt:
          issuer-uri: https://sso.example.com/auth/realms/example
      client:
        provider:
          # OAuth2 provider for accessing the KfreiRestApi
          kfrei-rest-api:
            issuer-uri: https://sso.example.com/auth/realms/example
        registration:
            # OAuth2 registration for accessing the KfreiRestApi
          kfrei-rest-api:
            authorization-grant-type: client_credentials
            client-id: example-id
            client-secret: example-secret
            # Requires: openid,roles
            scope: 
              - openid
              - roles
server:
  port: 8081
  shutdown: graceful
management:
  server:
    # Isolate operational endpoints from the main application traffic
    port: 8082
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
app:
  resourceserver:
    # OAuth2 client that holds the permission roles to verify
    client-id: example-id
  kfrei-rest-api:
    base-url: http://localhost:8080/api/v2
  swagger-ui:
    # OAuth2 provider for accessing the kfrei-mvg-eai
    token-url: https://sso.example.com/auth/realms/example/protocol/openid-connect/token
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  packages-to-scan: de.muenchen.oss.kfreimvgeai.rest
  paths-to-match: /api/v1/**
logging:
  level:
    de.muenchen.oss: INFO
    org.springframework: INFO
    root: WARN